# Change these first
owner: prakhardewangan2005-hash
repo: pulseboard-status

sites:
  - name: GitHub
    url: https://github.com

status-website:
  baseUrl: /pulseboard-status
  name: Pulseboard Status
  introTitle: "**Pulseboard Status** — uptime & latency monitor"
  introMessage: "Live monitoring powered by GitHub Actions (Upptime)."

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/prakhardewangan2005-hash/pulseboard-status




# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
